# -*- coding: utf-8 -*-
"""Estadística_179289.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s25uRmUoOIU2PMD6cxdO_utexH-I4Yid
"""

import numpy as np

# Datos de ejemplo
data = np.random.randint(0, 100, 10)  # 10 valores aleatorios entre 0 y 100
print(f"Datos: {np.sort(data)}")  # Ordenado para observar los percentiles

# Media
mean = np.mean(data)
print(f"Media: {mean}")

# Mediana
median = np.median(data)
print(f"Mediana: {median}")

# Desviación estándar
std_dev = np.std(data)
print(f"Desviación estándar: {std_dev}")

# Varianza
variance = np.var(data)
print(f"Varianza: {variance}")

# Máximo y mínimo
max_val = np.max(data)
min_val = np.min(data)
print(f"Máximo: {max_val}, Mínimo: {min_val}")

# Percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)
print(f"Percentil 25: {percentile_25}, Percentil 75: {percentile_75}")

# Correlación (ejemplo con dos conjuntos de datos)
data2 = np.random.randint(0, 100, 10)
correlation = np.corrcoef(data, data2)
print(f"Correlación: \n{correlation}")

# Histograma (requiere matplotlib)
import matplotlib.pyplot as plt
plt.hist(data, bins=5)  # bins define el número de barras en el histograma
plt.xlabel("Valor")
plt.ylabel("Frecuencia")
plt.title("Histograma de los datos")
plt.show()

# Ahora ejemplos de estadística con array de numpy de dos dimensiones

# Datos de ejemplo en un array de dos dimensiones (matriz)
data_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Media de todos los elementos
mean_all = np.mean(data_2d)
print(f"Media de todos los elementos: {mean_all}")

# Media por columnas
mean_cols = np.mean(data_2d, axis=0)
print(f"Media por columnas: {mean_cols}")

# Media por filas
mean_rows = np.mean(data_2d, axis=1)
print(f"Media por filas: {mean_rows}")

# Desviación estándar por columnas
std_cols = np.std(data_2d, axis=0)
print(f"Desviación estándar por columnas: {std_cols}")

# Varianza por filas
var_rows = np.var(data_2d, axis=1)
print(f"Varianza por filas: {var_rows}")


# Máximo y mínimo por columnas
max_cols = np.max(data_2d, axis=0)
min_cols = np.min(data_2d, axis=0)
print(f"Máximo por columnas: {max_cols}, Mínimo por columnas: {min_cols}")

# Percentiles por filas (percentil 50 = mediana)
percentile_50_rows = np.percentile(data_2d, 50, axis=1)
print(f"Percentil 50 (mediana) por filas: {percentile_50_rows}")

# Correlacion entre columnas (primera y segunda columna)
correlation = np.corrcoef(data_2d[:, 0], data_2d[:, 1])
print(f"Correlación entre la primera y segunda columna: \n{correlation}")

import numpy as np
import matplotlib.pyplot as plt

# Generar datos aleatorios para altura y cintura
altura = np.random.normal(loc=1.65, scale=0.1, size=100)  # Altura en metros (media 1.65, desviación estándar 0.1)
cintura = np.random.normal(loc=80, scale=10, size=100)  # Cintura en cm (media 80, desviación estándar 10)

# Crear el array de NumPy de dos dimensiones
datos_mexico = np.column_stack((altura, cintura))

# Análisis estadístico básico
media_altura = np.mean(altura)
media_cintura = np.mean(cintura)

mediana_altura = np.median(altura)
mediana_cintura = np.median(cintura)

desviacion_std_altura = np.std(altura)
desviacion_std_cintura = np.std(cintura)

# Imprimir los resultados estadísticos
print(f"Estadísticas para la Altura:")
print(f"  Media: {media_altura:.2f} m")
print(f"  Mediana: {mediana_altura:.2f} m")
print(f"  Desviación Estándar: {desviacion_std_altura:.2f} m")
print("\n")
print(f"Estadísticas para la Cintura:")
print(f"  Media: {media_cintura:.2f} cm")
print(f"  Mediana: {mediana_cintura:.2f} cm")
print(f"  Desviación Estándar: {desviacion_std_cintura:.2f} cm")

# Generación de histogramas
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))

# Histograma para la altura
ax1.hist(altura, bins=10, color='skyblue', edgecolor='black')
ax1.set_title("Histograma de Altura")
ax1.set_xlabel("Altura (m)")
ax1.set_ylabel("Frecuencia")

# Histograma para la cintura
ax2.hist(cintura, bins=10, color='lightgreen', edgecolor='black')
ax2.set_title("Histograma de Cintura")
ax2.set_xlabel("Cintura (cm)")
ax2.set_ylabel("Frecuencia")

# Mostrar gráficos
plt.tight_layout()
plt.show()

"""# Analice los datos_mexico utilizando estadística básica y genere un histograma para la altura y otro para la cintura"""